
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-26T13:19:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9934173910f7cc36def53dece1db4a27c52fadf6",
 "version": "2.6.0post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
